apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-template.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-template.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "app-template.servicePort" . }}
      protocol: TCP
      name: http
  selector:
    {{- include "app-template.selectorLabels" . | nindent 4 }}
